<?php
App::uses('AppModel', 'Model');
//App::uses('BlowfishPasswordHasher', 'Controller/Component/Auth' );

class User extends AppModel {

	public function bs($options = array())
	{
		$this->data = $options;
		debug($this->data);
		$alias = $this->alias;
//		debug($alias);
		$bbb = !empty($this->data[$alias]['password']);
//		debug($bbb);
		if($bbb) {
			$aaa = AuthComponent::password($this->data[$this->alias]['password']);
			$this->data[$this->alias]['password'] = AuthComponent::password($this->data[$this->alias]['password']);
		}
//		debug($aaa);
//		debug($this->data[$this->alias]['password']);
//		exit;
	return $aaa;
	}

	function beforeSave($options = array())
	{
	return;
		debug($this->data);
		$alias = $this->alias;
		$bbb = !empty($this->data[$alias]['password']);
		if($bbb) {
			$aaa = AuthComponent::password($this->data[$this->alias]['password']);
			$this->data[$this->alias]['password'] = AuthComponent::password($this->data[$this->alias]['password']);
//			$this->data[$this->alias]['password'] = Security::hash($this->data[$this->alias]['password']);
//			$this->data[$this->alias]['password'] = Security::hash($this->data[$this->alias]['password'], 'blowfish');
//        $passwordHasher = new BlowfishPasswordHasher();
//        $this->log($this->data[$this->alias]['password'] = $passwordHasher->hash($this->data[$this->alias]['password'] ));
		}

		debug($aaa);
		debug($this->data[$this->alias]['password']);
		debug('debug');exit;

//		return parent::beforeSave($options); // TODO: Change the autogenerated stub
	}

  public $validate = array(
    'username' => array(
      'ruleName1' => array(
        'rule' => array('lengthBetween', 6, 16 ),
        'message' => '6～16文字の間で入力して下さい。'
      ),
      'ruleName2' => array(
        'rule' => '/^[a-zA-Z0-9\s\x21-\x2f\x3a-\x40\x5b-\x60\x7b-\x7e]+$/u',
        'message' => '半角(英数・記号)のみ可能です。'
      ),
      'ruleName3' => array(
        'rule' => array('isUnique'),
        'message' => 'そのユーザー名はすでに使われています。'
      ),
    ),
    'password' => array(
      'rule' => array('lengthBetween', 1, 50 ),
      'message' => '1～50文字の間で入力して下さい。'
    ),
    'role' => array(
      'rule' => 'notBlank',
      'message' => 'この項目は必須入力です。'
    )
  );
}
